scan-type: source
disabled: false
ignore: []
output:
  - table
  - json
quiet: false
check-for-app-update: false
only-fixed: false
add-cpes-if-none: false
by-cve: false
db:
  auto-update: true
  validate-age: true
  max-allowed-built-age: 120h
