scan-type: source
disabled: false
ignore:
  - vulnerability: GHSA-5p4m-2wfm-xmqj
    include-aliases: true
    reason: 'Unfixable npm transitive vulnerability: unknown (unknown severity) as of 2026-08-27'
  - vulnerability: GHSA-6v5v-wf23-fmfq
    include-aliases: true
    reason: 'Unfixable npm transitive vulnerability: unknown (unknown severity) as of 2026-08-27'
output:
  - table
  - json
quiet: false
check-for-app-update: false
only-fixed: false
add-cpes-if-none: false
by-cve: false
db:
  auto-update: true
  validate-age: true
  max-allowed-built-age: 120h
